# Site settings
title: Dick Stein Practice Cup
description: "A weekly casual bowling competition for bragging rights and the coveted trophy."
url: "https://dicksteinpracticecup.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

# Collections
collections:
  players:
    output: true
    permalink: /players/:name/

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - start-jekyll.sh
  - node_modules
  - package.json
  - package-lock.json
  - netlify.toml
  - admin/
