# Site settings
title: Dick Stein Practice Cup
description: "A weekly casual bowling competition for bragging rights and the coveted trophy."
url: "https://dicksteinpracticecup.com"
author: Bruce, Joseph, Carol & Jacob

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# Exclude a file by listing it here.
exclude:
  - Gemfile
  - Gemfile.lock
