backend:
  name: github
  repo: bergerjacob/dicksteinpracticecup-website
  branch: main

# These are the default folders for the global Media tab
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "players"
    label: "Player Profiles"
    folder: "_players"
    create: true
    slug: "{{player_slug}}"
    media_folder: "/assets/images/players" # Keeps player photos organized
    public_folder: "/assets/images/players"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "player" }
      - { label: "Player Name (used as page title)", name: "title", widget: "string" }
      - { label: "URL and Filename Slug", name: "player_slug", widget: "string", hint: "e.g. 'bruce-rufener'. Must be unique." }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }

  - name: "winners_data"
    label: "Current & Past Champions"
    media_folder: "../assets/images/players"
    public_folder: "/assets/images/players"
    files:
      - file: "_data/winners.yml"
        label: "Winners List"
        name: "champions"
        fields:
          - name: "winners"
            label: "Edit Winners"
            widget: "list"
            label_singular: "Winner"
            fields:
              - { label: "Player Name", name: "name", widget: "string" }
              - { label: "Week Of (MM/DD/YY)", name: "week", widget: "string" }
              - { label: "Series Score", name: "series", widget: "number" }
              - { label: "Is Current Champion?", name: "current", widget: "boolean", default: false }
              - { label: "Optional Champion Photo", name: "image", widget: "image", required: false }

  - name: "trophy_locations_data"
    label: "Trophy Location Photos"
    media_folder: "../assets/images/trophy-locations"
    public_folder: "/assets/images/trophy-locations"
    files:
      - file: "_data/trophy_locations.yml"
        label: "Trophy Photos"
        name: "trophy_photos"
        fields:
          - name: "photos"
            label: "Edit Photos"
            label_singular: "Photo"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption (Optional)", name: "caption", widget: "string", required: false }

  - name: "highlights_data"
    label: "Video Highlights"
    files:
      - file: "_data/highlights.yml"
        label: "Videos"
        name: "video_highlights"
        fields:
          - name: "videos"
            label: "Video Clips"
            widget: "list"
            label_singular: "Video"
            allow_add: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL (from YouTube)", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
