backend:
  name: github
  repo: bergerjacob/dicksteinpracticecup-website
  branch: main

# These are the default folders for the global Media tab
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "players_data"
    label: "Player Profiles"
    description: "Click on the 'Players' item below to open the editor. NOTE: For season uploads/deletes, use the separate Season Management Tools page."
    # Corrected path to go up one directory from _data
    media_folder: "../assets/images/players"
    public_folder: "/assets/images/players"
    files:
      - file: "_data/players.yml"
        label: "Players"
        name: "players"
        fields:
          - name: "players"
            label: "Edit Players"
            widget: "list"
            label_singular: "Player"
            fields:
              - { label: "Player Name", name: "name", widget: "string" }
              - { label: "Slug (lowercase, no spaces, e.g. 'bruce-rufener')", name: "slug", widget: "string" }
              - { label: "Photo", name: "image", widget: "image" }
              - { label: "Bio", name: "bio", widget: "markdown" }

  - name: "winners_data"
    label: "Current & Past Champions"
    # Corrected path to go up one directory from _data
    media_folder: "../assets/images/players"
    public_folder: "/assets/images/players"
    files:
      - file: "_data/winners.yml"
        label: "Winners List"
        name: "champions"
        fields:
          - name: "winners"
            label: "Edit Winners"
            widget: "list"
            label_singular: "Winner"
            fields:
              - { label: "Player Name", name: "name", widget: "string" }
              - { label: "Week Of (MM/DD/YY)", name: "week", widget: "string" }
              - { label: "Series Score", name: "series", widget: "number" }
              - { label: "Is Current Champion?", name: "current", widget: "boolean", default: false }
              - { label: "Optional Champion Photo", name: "image", widget: "image", required: false }

  - name: "trophy_locations_data"
    label: "Trophy Location Photos"
    media_folder: "../assets/images/trophy-locations"
    public_folder: "/assets/images/trophy-locations"
    files:
      - file: "_data/trophy_locations.yml"
        label: "Trophy Photos"
        name: "trophy_photos"
        fields:
          - name: "photos"
            label: "Edit Photos"
            label_singular: "Photo"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption (Optional)", name: "caption", widget: "string", required: false }

  - name: "highlights_data"
    label: "Video Highlights"
    files:
      - file: "_data/highlights.yml"
        label: "Videos"
        name: "video_highlights"
        fields:
          - name: "videos"
            label: "Video Clips"
            widget: "list"
            label_singular: "Video"
            allow_add: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL (from YouTube)", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
