backend:
  name: github
  repo: bergerjacob/dicksteinpracticecup-website
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  # Collection 1: Player Profiles (now a single file)
  - name: "players_data"
    label: "Player Profiles"
    files:
      - file: "_data/players.yml"
        label: "Players"
        name: "players"
        fields:
          - name: "players"
            label: "Edit Players"
            widget: "list"
            fields:
              - { label: "Player Name", name: "name", widget: "string" }
              - { label: "Slug (lowercase, no spaces, e.g. 'bruce-rufener')", name: "slug", widget: "string" }
              - { label: "Photo", name: "image", widget: "image" }
              - { label: "Bio", name: "bio", widget: "markdown" }

  # Collection 2: Champions List (File Collection)
  - name: "winners_data"
    label: "Current & Past Champions"
    files:
      - file: "_data/winners.yml"
        label: "Winners List"
        name: "champions"
        fields:
          - name: "winners"
            label: "Edit Winners"
            widget: "list"
            fields:
              - { label: "Player Name", name: "name", widget: "string" }
              - { label: "Week Of (MM/DD/YY)", name: "week", widget: "string" }
              - { label: "Series Score", name: "series", widget: "number" }
              - { label: "Is Current Champion?", name: "current", widget: "boolean", default: false }
              - { label: "Optional Champion Photo", name: "image", widget: "image", required: false }

  # Collection 3: Video Highlights (File Collection)
  - name: "highlights_data"
    label: "Video Highlights"
    files:
      - file: "_data/highlights.yml"
        label: "Videos"
        name: "video_highlights"
        fields:
          - name: "videos"
            label: "Video Clips"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL (from YouTube)", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
